### ISSUE TITLE
Divide by zero error with compression levels under 10

### ISSUE THREAD

**Issue by NiceneNerd** [gcnhax/yaz0-rs#3]
The following code example panics from attempting to divide by zero:
```rust
fn write_yaz0_sarc_to_file<P: AsRef<Path>>(sarc: &SarcFile, path: P) -> GeneralResult<()> {
    let mut file = File::create(path.as_ref())?;
    let writer = Yaz0Writer::new(&mut file);
    let mut temp = vec![];
    sarc.write(&mut temp)?;
    writer
        .compress_and_write(&temp, yaz0::CompressionLevel::Lookahead { quality: 7 })
        .map_err(|e| Box::from(e))
}
```
I experimented, and it applies when the compression level is any number lower than 10. It comes from [this line](https://github.com/gcnhax/yaz0-rs/blob/73432b43a7fb227b2c6f17d9b6c06bab116c8a3c/src/deflate.rs#L155) in `deflate.rs`:
```rust
let lookback = MAX_LOOKBACK / (quality as f32 / 10.).floor() as usize;
```
It does seem that using `floor()` here would inevitably make all lower compression levels trigger division by zero.

**Comment by barzamin** [comment]
oh wow that's a foolish mistake on my part! pretty sure the `.floor()` was supposed to wrap the whole thing and not just the denominator, which is exactly what you did in #4!

(also i'm sorry i didn't see this until now! i'm incredibly happy to know that people are actually playing with this library :smiley:)

**Comment by barzamin** [comment]
@NiceneNerd I brainfarted and forgot to cut a new release. It's up on crates now :)
